# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureSelectIntersectSample
                                 A QGIS plugin
 選択したフューチャーと交差するフューチャーを選択するサンプル
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-11
        copyright            : (C) 2020 by unemployed
        email                : chiakikungm@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FeatureSelectIntersectSample class from file FeatureSelectIntersectSample.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .featureselectintersect_sample import FeatureSelectIntersectSample
    return FeatureSelectIntersectSample(iface)
