# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EditFeatureSample
                                 A QGIS plugin
 フューチャーを編集するサンプルです
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-26
        copyright            : (C) 2020 by Chiakikun
        email                : chiakikungm@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EditFeatureSample class from file EditFeatureSample.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .editfeature_sample import EditFeatureSample
    return EditFeatureSample(iface)
