# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GetRasterValueSample
                                 A QGIS plugin
 マウスカーソル下のラスタの値をツールチップで表示します
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-25
        copyright            : (C) 2020 by Chiakikun
        email                : chiakikungm@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GetRasterValueSample class from file GetRasterValueSample.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .getrastervalue_sample import GetRasterValueSample
    return GetRasterValueSample(iface)
