# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ScreenShotSample2
                                 A QGIS plugin
 ベクタレイヤをフューチャー毎にスクリーンショットで保存するサンプルの改良版。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-29
        copyright            : (C) 2019 by Chiakikun
        email                : chiakikungm@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ScreenShotSample2 class from file ScreenShotSample2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .screenShot_Sample2 import ScreenShotSample2
    return ScreenShotSample2(iface)
