# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FeatureSelectExprSampleDialog
                                 A QGIS plugin
 フューチャーをクエリ式で選択します。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-26
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Chiakikun
        email                : chiakikungm@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import QtCore
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.PyQt.QtCore import QSettings

import os
import qgis.core

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'featureselectexpr_sample_dialog_base.ui'))


class FeatureSelectExprSampleDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        super(FeatureSelectExprSampleDialog, self).__init__(parent)
        self.setupUi(self)

        self.iface = qgis.utils.iface
        self.canvas = self.iface.mapCanvas()


    def cancelPush(self):
        self.close()


    def closeEvent(self, e):
        QSettings().setValue("/Qgis/dockAttributeTable", self.oldsetting)


    def showEvent(self, e):
        self.layer = self.iface.activeLayer()
        if type(self.layer) is not qgis.core.QgsVectorLayer:
            QMessageBox.about(None, '警告', 'ベクタレイヤを選択してから実行してください')
            return

        self.execButton.setEnabled(False)
        self.saveButton.setEnabled(False)

        self.layer.removeSelection()

        # コンボボックスにフィールド名を設定する
        self.fieldsBox.clear()
        for s in self.layer.fields():
            self.fieldsBox.addItem(s.name())

        self.oldsetting = QSettings().value("/Qgis/dockAttributeTable")  # 一時退避


    def queryChange(self):
        self.layer.removeSelection()
        self.execButton.setEnabled(False)
        self.saveButton.setEnabled(False)


    def testPush(self):
        self.query = ''

        # queryでフューチャーが選択できるか
        query = '"' + self.fieldsBox.currentText() + '" ' + self.queryEdit.text()
        features = self.layer.getFeatures(qgis.core.QgsFeatureRequest().setFilterExpression(query))
        if len(list(features)) == 0:
            QMessageBox.information(None, '警告', '指定したクエリではフューチャーを抽出できませんでした')
            return
        # できました
        self.query = query
        QtWidgets.QMessageBox.information(None, '情報', 'エラーなし')
        self.execButton.setEnabled(True)
        self.saveButton.setEnabled(True)


    def execPush(self):
        QSettings().setValue("/Qgis/dockAttributeTable", True) # 属性テーブルをドッキング状態で表示させる
        self.layer.selectByExpression(self.query)              # 式で抽出できるフューチャーを選択
        self.iface.showAttributeTable(self.layer, self.query)  # 式で抽出できるフューチャーの属性のみテーブルに表示


    def savePush(self):
        path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "ファイルを保存します", "", "GeoPackage (*.gpkg)")
        if path:
            qgis.core.QgsVectorFileWriter.writeAsVectorFormat(self.layer, path, "System", onlySelected=True) # 選択しているフューチャーのみ保存
