# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddFeatureSampleDialog
                                 A QGIS plugin
 AddFeatureのSampleです
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-23
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Chiakikun
        email                : chiakikungm@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import QtCore, QtGui
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtGui import QColor
import os
import qgis.core
from datetime import datetime

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'maptoolemitpoint_sample_dialog_base.ui'))


class AddFeatureSampleDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, iface, layerName, userName, parent=None):
        super(AddFeatureSampleDialog, self).__init__(parent)
        self.setupUi(self)

        self.canvas = iface.mapCanvas()

        # キャンバスウィンドウ上でのマウスイベントの設定
        self.mouseEventSample = qgis.gui.QgsMapToolEmitPoint(self.canvas)

        self.layer = qgis.core.QgsProject.instance().mapLayersByName(layerName)[0]

        # 対象レイヤにフィールド「更新者」を追加する
        field_index = self.layer.fields().indexFromName('更新者')
        if field_index == -1:
            self.layer.startEditing()
            self.layer.dataProvider().addAttributes([qgis.core.QgsField('更新者', QVariant.String)])
            self.layer.commitChanges()

        self.objType = self.layer.geometryType()
        self.userName = userName


    def unsetTool(self):
        self.pushButton_Exec.setChecked(False)


    def closeEvent(self, e):
        try:
            self.pushButton_Exec.setChecked(False)
            for i in range(0, len(self.myRubberBands)):
                self.canvas.scene().removeItem(self.myRubberBands[i])
            self.myRubberBand.reset(True)
        except:
            pass
 

    def pushClose(self):
        self.close()


    def pushExec(self, checked):
        if checked == True:
            self.mouseEventSample.canvasClicked.connect(self.mouseClick)
            self.mouseEventSample.canvasDoubleClickEvent = self.mouseDoubleClick
            self.mouseEventSample.canvasMoveEvent = self.canvasMoveEvent        
            self.canvas.setMapTool(self.mouseEventSample)

            self.canvas.mapToolSet.connect(self.unsetTool)
            self.pushButton_Exec.setText('実行中')

            self.myRubberBand = None
            self.myRubberBands = [] # 使用済みのラバーバンドを格納しておく場所
        else:
            try: # 右クリックしてmyRubberBandを解放していた場合は例外発生するので。
                for i in range(0, len(self.myRubberBands)):
                    self.canvas.scene().removeItem(self.myRubberBands[i])
                self.myRubberBand.reset(True)
            except:
                pass

            self.pushButton_Exec.setText('実行')

            self.canvas.mapToolSet.disconnect(self.unsetTool)
            self.canvas.unsetMapTool(self.mouseEventSample)
            self.mouseEventSample.canvasClicked.disconnect(self.mouseClick)


    def canvasMoveEvent(self, event):
        if self.myRubberBand == None: # 一度も左ボタンをクリックしてない時にこのメソッドが呼ばれた場合
            return

        # 地物の描画中に、マウスカーソルを追って形状が変わるように
        point = self.canvas.getCoordinateTransform().toMapCoordinates(event.pos())
        self.myRubberBand.movePoint(point)


    def mouseClick(self, currentPos, clickedButton ):
        # 地物の最初の一点目
        if clickedButton == QtCore.Qt.LeftButton and self.myRubberBand == None:
            self.myRubberBand = qgis.gui.QgsRubberBand( self.canvas, self.objType )
            self.myRubberBand.setColor( QColor(78, 97, 114, 190) )
            self.myRubberBand.addPoint( qgis.core.QgsPointXY(currentPos) )

        # 地物の二点目以降
        if clickedButton == QtCore.Qt.LeftButton and self.myRubberBand.numberOfVertices() > 0:
            self.myRubberBand.addPoint( qgis.core.QgsPointXY(currentPos) )

        # __init__で作成した仮想レイヤのレコード作成
        if clickedButton == QtCore.Qt.RightButton:
            # フィールド設定
            qf = qgis.core.QgsFields()
            for field in self.layer.fields():
                qf.append(qgis.core.QgsField(str(field.name()), typeName=field.typeName()))
            record = qgis.core.QgsFeature(qf) 

            # ラバーバンドで作成した地物をセットする
            if self.myRubberBand != None: self.myRubberBand.removeLastPoint() # 右クリックした時のカーソル位置のポイントは含めない
            self.myRubberBands.append(self.myRubberBand)
            if self.objType == qgis.core.QgsWkbTypes.GeometryType.PolygonGeometry:
                record.setGeometry(self.RubberBandsToPolygon())
            elif self.objType == qgis.core.QgsWkbTypes.GeometryType.LineGeometry:
                record.setGeometry(self.RubberBandsToLine())
            elif self.objType == qgis.core.QgsWkbTypes.GeometryType.PointGeometry:
                record.setGeometry(self.RubberBandsToPoint())

            # 属性をセットする
            record['更新者'] = self.userName

            # 作成したレコードをレイヤに追加
            self.layer.dataProvider().addFeatures([record])
            self.layer.updateExtents() # これが無いと『レイヤの領域にズーム』した時に、レイヤの最初のオブジェクト部分しかズームされない

            # キャンバスにオブジェクトを表示する      
            qgis.core.QgsProject.instance().addMapLayers([self.layer])
            self.canvas.refreshAllLayers()

            self.myRubberBand = None
            self.myRubberBands = []
            self.canvas.refreshAllLayers()


    def mouseDoubleClick(self, event):
        if self.myRubberBand == None:
            return

        if self.objType == qgis.core.QgsWkbTypes.GeometryType.PointGeometry:
            return

        if self.myRubberBand.numberOfVertices() == 2:
            self.myRubberBand = None
            return

        self.myRubberBand.removeLastPoint()

        self.myRubberBands.append(self.myRubberBand)
        self.myRubberBand = None 


    def RubberBandsToPolygon(self):
        mpol = []
        for i in range(0, len(self.myRubberBands)):
            if self.myRubberBands[i] == None: continue
            mpol.append([[]])
            for pnts in self.myRubberBands[i].asGeometry().asPolygon(): 
                for pnt in pnts:
                    mpol[len(mpol)-1][0].append(pnt)
            self.canvas.scene().removeItem(self.myRubberBands[i])
        return qgis.core.QgsGeometry().fromMultiPolygonXY(mpol) 


    def RubberBandsToLine(self):
        mline = []
        for i in range(0, len(self.myRubberBands)):
            if self.myRubberBands[i] == None: continue
            mline.append([])
            for pnts in self.myRubberBands[i].asGeometry().asPolyline(): 
                mline[len(mline)-1].append(pnts)
            self.canvas.scene().removeItem(self.myRubberBands[i])
        return qgis.core.QgsGeometry().fromMultiPolylineXY(mline) 


    def RubberBandsToPoint(self):
        mpnt = []
        for i in range(0, len(self.myRubberBands)):
            if self.myRubberBands[i] == None: continue
            for pnt in self.myRubberBands[i].asGeometry().asMultiPoint():
                mpnt.append(pnt)
            self.canvas.scene().removeItem(self.myRubberBands[i])
        print(mpnt)
        return qgis.core.QgsGeometry().fromMultiPointXY(mpnt) 
